### PR TITLE
Sync with midstream repository

### PR DESCRIPTION
**Pull request by gparvin**
Changes being synced are mostly for currency and logging updates.  A few bug fixes too.  See the commits for 
additional details.

### CODE REVIEW

**Review by dhaiducek — APPROVED** [review]

**Comment by dhaiducek** [comment]
Shoot. I forgot to put a `/hold` on this so it wouldn't be squashed. Oops. 🤦

**Comment by dhaiducek** [comment]
Do we want to roll it back and try again? . . .

**Comment by mprahl** [comment]
> Do we want to roll it back and try again? . . .

@gparvin could you please do that?

**Pull request merged**
