### PR TITLE
Support an alternative managed cluster namespace on the Hub

### PR DESCRIPTION
**Pull request by mprahl**
This is required for running the Policy addon in hosted mode because the
namespace on the hosting cluster might be different than the cluster
name.

Related:
https://github.com/stolostron/backlog/issues/24362

### CODE REVIEW

**Review by gparvin — APPROVED** [review]
Looks good!

**Review by JustinKuli — APPROVED** [review]
/remove-hold

Looks like Matt's comment to remove the hold earlier didn't work...

**Pull request merged**
